### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by whitehorse2022** [LinglanZhao/BiDistFSCIL#1]
The pre-trained model tar file can`t be decompressed，could you check it?

**Comment by LinglanZhao** [comment]
Thank you for your interest!
The pre-trained model does not need to be decompressed and the only step to be done is putting the file into the path: experiment/mini_imagenet

**Comment by whitehorse2022** [comment]
> Thank you for your interest! The pre-trained model does not need to be decompressed and the only step to be done is putting the file into the path: experiment/mini_imagenet

Your work is very meaningful， thanks！
