### ISSUE TITLE
实验结果不符合原文

### ISSUE THREAD

**Issue by L-JunJie** [LinglanZhao/BiDistFSCIL#6]
作者您好，我使用了1-shot来训练mini_imagenet，然而最终测试结果为 [74.03% 69.09% 64.64% 61.03% 57.74% 54.62% 51.82% 49.76% 48.25%]

**Comment by LinglanZhao** [comment]
1. The training of our method is standard supervised training which does not involve the concept of "shot". Please refer to the pretrain scripts for more details.
2. The results on mini-ImageNet in our paper are conducted on 5-shot instead of 1-shot. Please refer to our paper for more details.
